### ISSUE TITLE
add ability to disable/remove modules

### ISSUE THREAD

**Issue by luizbills** [tachyons-css/generator#76]
example:

```json
{
	"disable": [
		"aspect-ratios",
		"tables"
	]
}

**Comment by marcofugaro** [comment]
This should already work, from the readme:

> You can also omit the partials you don't need with the key skipModules, for example if you don't want normalize.css in the bundle you can do:

``` js
{
  "skipModules": ["normalize"]
}
```

**Comment by marcofugaro** [comment]
Yup, it works as the example
