### ISSUE TITLE
Is this repo not mantained anymore?

### ISSUE THREAD

**Issue by marcofugaro** [tachyons-css/generator#93]
Some time ago I send [this PR](https://github.com/tachyons-css/generator/pull/92) that solves some of the major issues with the project, but it hasn't been looked or reviewed since.

You don't have any time to work on this repo? Do you need mantainers?

**Comment by johno** [comment]
Hey, thanks for the PRs!  This repo is maintained, I've just been a bit short on time lately. I've invited you to be a collaborator on this repo if you have time to make improvements. Thanks!

**Comment by marcofugaro** [comment]
Hey thanks man!
